// script.js
const langData = {
    "ru": {
      "servise_card3_page": "ТЭНС терапия",
      "servise_card3_page_text1": "Боль обычно свидетельствует о том, что в организме что-то идет не так. Иногда она становится хронической, из-за чего значительно снижается качество жизни и в целом ограничиваются возможности человека. Одним из инновационных и максимально безопасных методов устранения болезненности является импульсно-токовая терапия. Ее также называют ТЭНС — расшифровывается, как транскутанная электронейронная стимуляция. Метод лечения безмедикаментозный, безоперационный, неинвазивный и подходящий практически всем пациентам.      ",
      "servise_card3_page_text2": "Суть и действие ТЭНС терапии",
      "servise_card3_page_text3": "Импульсно-токовая стимуляция — это методика, которая предполагает подачу электрического низкочастотного тока через кожу к болезненным участкам. Электрические импульсы в виде коротких сигналов воздействуют на нервы, связанные с мышцами в нервно-мышечные пучки. В результате стимуляция электротоком нервных волокон на нее дают ответ и мышечные ткани. Это помогает снять напряжение и спазм, разблокировать зажатые корешки нервов и эффективно снизить болевые ощущения. Работает это так:",
      "servise_card3_page_ul1_li1": "На коже пациента в местах, где наиболее выражена боль, устанавливаются аппликаторы с электродами.",
      "servise_card3_page_ul1_li2": "К ним по тонким проводам подается электрический ток с безопасными для человека параметрами.",
      "servise_card3_page_ul1_li3": "Источник импульсов — специальный электростимулятор. В нашем Центре телесной терапии применяется передовое и надежное оборудование с максимальным уровнем безопасности для пациентов и персонала.",
      "servise_card3_page_ul1_li4": "Электрический импульс провоцирует отрицательное мышечное сокращение, т.е. не вызванное нагрузкой. При этом возникает двигательное возбуждение.",
      "servise_card3_page_text4": "Продолжительность одной процедуры составляет до 20 минут. Для лечения одной зоны нужен курс из 3-6 сеансов. Во время них пациенты ощущают легкое постукивание в местах, на которых проводится ТЭНС терапия. Если есть сильное воспаление мышечных волокон, возможно ощущение коротких толчкообразных болевых явлений.",
      "servise_card3_page_text5": "Где применяется импульсно-токовая терапия?",
      "servise_card3_page_text6": "Методика ТЭНС, как часть физиотерапевтического лечения, применяется:",
      "servise_card3_page_ul1_li5": "для купирования болевого синдрома — как острого, так и хронического;",
      "servise_card3_page_ul1_li6": "для восстановления мышечной силы, не создавая нагрузку на болезненные участки и суставы;",
      "servise_card3_page_ul1_li7": "поддержание мышц в нормальном функциональном состоянии, когда нужна профилактика их атрофии, например, при параличе, инсульте и пр.;",
      "servise_card3_page_ul1_li8": "для профилактики послеоперационной мышечной слабости, особенно, если больные долго вынужденно находятся в лежачем положении;",
      "servise_card3_page_ul1_li9": "в спортивной медицине.",
      "servise_card3_page_text7": "Показания для ТЭНС терапии",
      "servise_card3_page_text8": "Импульсно-токовая стимуляция применяется для пациентов с патологиями неврологического, травматологического и ортопедического профилей:",
      "servise_card3_page_ul1_li10": "переломы;",
      "servise_card3_page_ul1_li11": "искривление позвоночника — гиперлордоз, сколиоз и пр.;",
      "servise_card3_page_ul1_li12": "атрофия мышц, в т.ч. после длительного периода без движения;",
      "servise_card3_page_ul1_li13": "пяточная шпора;",
      "servise_card3_page_ul1_li14": "контрактуры суставов;",
      "servise_card3_page_ul1_li15": "тендинопатии;",
      "servise_card3_page_ul1_li16": "боль при остеохондрозе;",
      "servise_card3_page_ul1_li17": "боль и напряжение при спазмировании мышц из-за стресса, тревожного состояния и пр.;",
      "servise_card3_page_ul1_li18": "невриты и невралгии;",
      "servise_card3_page_ul1_li19": "миозиты и т.д.",
      "servise_card3_page_text9": "Процедура блокирует передачу сигнала боли от нерва к мозгу. Одновременно с этим увеличивается выработка эндорфина, который тоже имеет анальгезирующий эффект. В результате терапия подавляет воспаление, нормализует тонус мышц и возобновляет их полноценное кровоснабжение.",
      "servise_card3_page_text10": "Плюсы импульсно-токовой электростимуляции",
      "servise_card3_page_text11": "Методика ТЭНС имеет значимые преимущества:",
      "servise_card3_page_ul1_li20": "Комплексно воздействует на пораженный участок. В нем мышцы приходят в нормальный тонус, усиливается кровообращение, улучшается иннервация и состояние сосудов.",
      "servise_card3_page_ul1_li21": "Отсутствие инвазивного подхода. Аппликаторы с электродами просто прикладываются к коже. Не нужно никаких проколов и разрезов.",
      "servise_card3_page_ul1_li22": "Не возникает хроническая усталость мускулатуры. Это возможно за счет того, что стимулирующий электроток имеет низкую частоту.",
      "servise_card3_page_text12": "Противопоказания к ТЭНС терапии",
      "servise_card3_page_text13": "Несмотря на универсальность и безопасность метода, для него все же есть некоторые ограничения:",
      "servise_card3_page_ul1_li23": "Наличие имплантов-кардиостимуляторов.",
      "servise_card3_page_ul1_li24": "Сбои сердечного ритма, в т.ч. аритмии.",
      "servise_card3_page_ul1_li25": "Тромбозы.",
      "servise_card3_page_ul1_li26": "Тромбофлебит.",
      "servise_card3_page_ul1_li27": "Открытые переломы.",
      "servise_card3_page_ul1_li28": "Беременность и менструация — аппликаторы не накладываются в область живота и таза.",
      "servise_card3_page_text14": "Специалисты нашего Центра телесной терапии проводят процедуру импульсно-токовой терапии с учетом индивидуальных особенностей и потребностей каждого пациента. Врач четко локализует места для размещения аппликаторов, определяет режим подачи импульсов, устанавливает время сеанса и контролирует состояние пациента во время и после процедуры.",
      "servise_card3_page_text15": "Приходите на импульсно-токовую терапию в Ташкенте в наш центр. Здесь вас ждут компетентные специалисты с медицинским образование и большим опытом, безопасная и эффективная физиотерапия на инновационном оборудовании, а также избавление от боли, дискомфорта и скованности.",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",


    },
    "en": {
      "servise_card3_page": "TENS therapy",
      "servise_card3_page_text1": "Pain usually indicates that something is wrong in the body. Sometimes it becomes chronic, due to which the quality of life is significantly reduced and, in general, the capabilities of a person are limited. One of the innovative and safest methods for eliminating pain is pulsed current therapy. It is also called TENS, which stands for transcutaneous electrical neuron stimulation. The method of treatment is drug-free, non-surgical, non-invasive and suitable for almost all patients.",
      "servise_card3_page_text2": "The essence and effect of TENS therapy",
      "servise_card3_page_text3": "Pulse current stimulation is a technique that involves the supply of an electrical low-frequency current through the skin to painful areas. Electrical impulses in the form of short signals act on the nerves associated with the muscles in the neuromuscular bundles. As a result, electrical stimulation of nerve fibers also gives an answer to muscle tissue. It helps relieve tension and spasm, unblock pinched nerve roots and effectively reduce pain. It works like this:",
      "servise_card3_page_ul1_li1": "On the patient's skin in places where the pain is most pronounced, applicators with electrodes are installed.",
      "servise_card3_page_ul1_li2": "Electric current is supplied to them through thin wires with parameters that are safe for humans.",
      "servise_card3_page_ul1_li3": "The source of impulses is a special electrical stimulator. Our Body Therapy Center uses advanced and reliable equipment with the highest level of safety for patients and staff.",
      "servise_card3_page_ul1_li4": "An electrical impulse provokes a negative muscle contraction, i.e. not caused by the load. In this case, motor excitation occurs.",
      "servise_card3_page_text4": "The duration of one procedure is up to 20 minutes. For the treatment of one zone, a course of 3-6 sessions is needed. During them, patients feel a slight tapping in the places where TENS therapy is performed. If there is severe inflammation of the muscle fibers, there may be a sensation of short jerky pain phenomena.",
      "servise_card3_page_text5": "Where is pulsed current therapy used?",
      "servise_card3_page_text6": "The TENS technique, as part of physiotherapy treatment, is used:",
      "servise_card3_page_ul1_li5": "for the relief of pain - both acute and chronic;",
      "servise_card3_page_ul1_li6": "to restore muscle strength without creating a load on painful areas and joints;",
      "servise_card3_page_ul1_li7": "maintaining muscles in a normal functional state when prevention of their atrophy is needed, for example, with paralysis, stroke, etc .;",
      "servise_card3_page_ul1_li8": "for the prevention of postoperative muscle weakness, especially if patients are forced to lie down for a long time;",
      "servise_card3_page_ul1_li9": "in sports medicine.",
      "servise_card3_page_text7": "Indications for TENS therapy",
      "servise_card3_page_text8": "Pulse-current stimulation is used for patients with pathologies of neurological, traumatological and orthopedic profiles:",
      "servise_card3_page_ul1_li10": "fractures;",
      "servise_card3_page_ul1_li11": "curvature of the spine - hyperlordosis, scoliosis, etc.;",
      "servise_card3_page_ul1_li12": "muscle atrophy, incl. after a long period of inactivity;",
      "servise_card3_page_ul1_li13": "heel spur;",
      "servise_card3_page_ul1_li14": "joint contractures;",
      "servise_card3_page_ul1_li15": "tendinopathies;",
      "servise_card3_page_ul1_li16": "pain in osteochondrosis;",
      "servise_card3_page_ul1_li17": "pain and tension during muscle spasms due to stress, anxiety, etc.;",
      "servise_card3_page_ul1_li18": "neuritis and neuralgia;",
      "servise_card3_page_ul1_li19": "myositis, etc.",
      "servise_card3_page_text9": "The procedure blocks the transmission of the pain signal from the nerve to the brain. At the same time, the production of endorphins increases, which also has an analgesic effect. As a result, therapy suppresses inflammation, normalizes muscle tone and restores their full blood supply.",
      "servise_card3_page_text10": "Advantages of pulse-current electrical stimulation",
      "servise_card3_page_text11": "The TENS technique has significant advantages:",
      "servise_card3_page_ul1_li20": "It has a complex effect on the affected area. In it, the muscles come to a normal tone, blood circulation increases, innervation and the state of blood vessels improve.",
      "servise_card3_page_ul1_li21": "No invasive approach. Applicators with electrodes are simply applied to the skin. No punctures or incisions needed.",
      "servise_card3_page_ul1_li22": "There is no chronic muscle fatigue. This is possible due to the fact that the stimulating current has a low frequency.",
      "servise_card3_page_text12": "Contraindications for TENS therapy",
      "servise_card3_page_text13": "Despite the versatility and safety of the method, it still has some limitations:",
      "servise_card3_page_ul1_li23": "The presence of pacemaker implants.",
      "servise_card3_page_ul1_li24": "Heart rhythm failures, incl. arrhythmias.",
      "servise_card3_page_ul1_li25": "Thrombosis.",
      "servise_card3_page_ul1_li26": "Thrombophlebitis.",
      "servise_card3_page_ul1_li27": "Open fractures.",
      "servise_card3_page_ul1_li28": "Pregnancy and menstruation - the applicators are not applied to the abdomen and pelvis.",
      "servise_card3_page_text14": "The specialists of our Body Therapy Center carry out the procedure of pulsed current therapy, taking into account the individual characteristics and needs of each patient. The doctor clearly localizes the places for placing the applicators, determines the pulse delivery mode, sets the session time and controls the patient's condition during and after the procedure.",
      "servise_card3_page_text15": "Come to our center for pulsed current therapy in Tashkent. Here you will find competent specialists with medical education and extensive experience, safe and effective physiotherapy on innovative equipment, as well as getting rid of pain, discomfort and stiffness.",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
  
    },
  };
  
  const langElements = document.querySelectorAll('.lang');
  
  function changeLanguage(language) {
    selectedLanguage = language;
    langElements.forEach(el => {
      el.textContent = langData[selectedLanguage][el.getAttribute('key')];
    });
  }
  
  
  
  // Tilni qayta belgilash
  let selectedLanguage = 'ru';
  langElements.forEach(el => {
    el.textContent = langData[selectedLanguage][el.getAttribute('key')];
  });
  
  const langButtons = document.querySelectorAll('.lang-button');
  langButtons.forEach(btn => {
  btn.addEventListener('click', () => {
    changeLanguage(btn.dataset.lang);
    langButtons.forEach(btn => {
      btn.classList.remove('active_lang');
    });
    btn.classList.add('active_lang');
  });
  });
  