// script.js
const langData = {
  "ru": {
    "servise_card1_page": "Мануальная терапия",
    "servise_card1_page_text1": "Современному обществу свойственно повышенное внимание к здоровью, однако при этом «помолодели» и различные болезни. Это связано и с усиленным нервным напряжением, и с длительным сидячим положением за работой или, наоборот, повышенными физическими нагрузками, а также с постоянным использованием мобильных гаджетов, провоцирующее изменение осанки. В результате возникают защемления нервов, перенапряжение и укорочение одних мышц на фоне растяжения и ослабления других, а также неестественное искривление позвоночника и нарушение его структур. Для борьбы с этими проблемами применяется мануальная терапия",
    "servise_card1_page_text2": "Суть мануальной терапии",
    "servise_card1_page_text3": "Дословно мануальная терапия переводится, как «лечение руками». Это означает, что врач с помощью своих рук и специальных техник воздействует на опорно-двигательный аппарат, чтобы способствовать лечению текущих проблем с ним. Методика полностью безоперационная и не требует каких-либо инъекций. Хотя мануальную терапию принято считать разделом нетрадиционной медицины, она используется и в традиционных направлениях — ортопедии, неврологии, нейрофизиологии. Также некоторые упражнения и техники перешли в спортивную медицину и ЛФК.",
    "servise_card1_page_text4": "Первоначально мануальная терапия была направлена на лечение только опорно-двигательного аппарата. Сейчас же к ней относится и висцеральная остеопатия, воздействующая на внутренние органы, а также краниосакральная терапия, влияющая на голову. Когда нужна помощь мануального терапевта?",
    "servise_card1_page_ul1": "Обращайтесь в наш Центр телесной терапии для консультации мануального терапевта в таких случаях:",
    "servise_card1_page_ul1_li1": "Много времени проводите в дороге, в т.ч. за рулем автомобиля и в поездах.",
    "servise_card1_page_ul1_li2": "Иногда или регулярно поднимаете большие грузы.",
    "servise_card1_page_ul1_li3": "После резкого поворота есть дискомфорт в спине, шее, конечностях.",
    "servise_card1_page_ul1_li4": "Есть ощущение онемевших рук, холодеют ноги.",
    "servise_card1_page_ul1_li5": "Вы ведете малоподвижный образ жизни или много сидите на работе.",
    "servise_card1_page_ul1_li6": "Вы ощущаете себя скованным физически и морально.",
    "servise_card1_page_ul1_li7": "Есть замкнутость, раздражительность, депрессивное состояние.",
    "servise_card1_page_ul1_li8": "Имеется лишний вес.",
    "servise_card1_page_ul1_li9": "По утрам ощущается зажатость в мышцах.",
    "servise_card1_page_ul1_li10": "На работе или в повседневной жизни много стрессов.",
    "servise_card1_page_ul1_li11": "Вы тренируетесь в тренажерном зале, а после занятий есть боли и дискомфорт в теле.",
    "servise_card1_page_text5": "Показания для применения мануальной терапии",
    "servise_card1_page_text6": "Мы рекомендуем записаться на мануальную терапию в Ташкенте в наш Центр телесной терапии, если имеются такие показания:",
    "servise_card1_page_ul1_li12": "боль и неприятные ощущения в спине — зачастую спровоцированы остеохондрозом, гиперлордозом, сколиозом;",
    "servise_card1_page_ul1_li13": "гипертония или гипотония;",
    "servise_card1_page_ul1_li14": "бессонница;",
    "servise_card1_page_ul1_li15": "головокружения, мигрени;",
    "servise_card1_page_ul1_li16": "хроническая усталость и высокая утомляемость;",
    "servise_card1_page_ul1_li17": "слабость и онемение в конечностях;",
    "servise_card1_page_ul1_li18": "искривление позвоночника;",
    "servise_card1_page_ul1_li19": "грыжа межпозвоночных дисков;",
    "servise_card1_page_ul1_li20": "радикулит;",
    "servise_card1_page_ul1_li21": "шейный прострел;",
    "servise_card1_page_ul1_li22": "межреберная невралгия;",
    "servise_card1_page_ul1_li23": "боли в копчике;",
    "servise_card1_page_ul1_li24": "смещение межпозвоночных дисков;",
    "servise_card1_page_ul1_li25": "остеохондроз, который проявляется головными болями, болями в сердце, сбоями в работе внутренних органов;",
    "servise_card1_page_ul1_li26": "артрозы, снижающие амплитудность суставных движений;",
    "servise_card1_page_ul1_li27": "ограничение подвижности из-за перенапряжения мышц",
    "servise_card1_page_ul1_li28": "устойчивые мышечные спазмы;",
    "servise_card1_page_ul1_li29": "восстановление после травм на опорно-двигательном аппарате;",
    "servise_card1_page_ul1_li30": "невроз и неврастения;",
    "servise_card1_page_ul1_li31": "нейроциркуляторная дистония;",
    "servise_card1_page_ul1_li32": "снижение качества зрения, ухудшение памяти и внимания.",
    "servise_card1_page_text7": "Отличие мануальной терапии от массажа",
    "servise_card1_page_text8": "Ошибочно приравнивать мануальную терапию к массажу, т.к. они радикально отличаются. Массажные движения направлены на проработку мягких тканей, а действия мануального терапевта — на позвоночник, суставы и кости. Массаж может помочь снять напряжение в мышцах и ослабить болевые ощущения при искривлениях позвоночника. Зато мануальная терапия способствует устранению причин этих проявлений, поэтому она имеет более сильное влияние на организм. Именно поэтому «лечение руками» должен проводить только врач с достаточным опытом после осмотра пациента и сбора анамнеза.",
    "servise_card1_page_text9": "Методы лечения в мануальной терапии",
    "servise_card1_page_text10": "Для каждого пациента врач подбирает комплекс методик индивидуально, чтобы за короткое время достичь выраженного положительного результата и облегчить состояние больного. Основное внимание специалиста направлено на лечение неврологических проявлений заболеваний, а в дальнейшем — на реабилитацию пациента. Для этого используются такие методики:",
    "servise_card1_page_ul1_li33": "мануальная диагностика и осмотр;",
    "servise_card1_page_ul1_li34": "мануальная терапия суставов и позвоночного столба;",
    "servise_card1_page_ul1_li35": "иглоукалывание;",
    "servise_card1_page_ul1_li36": "постизометрическая релаксация;",
    "servise_card1_page_ul1_li37": "МЭТ;",
    "servise_card1_page_ul1_li38": "упражнения хатха-йоги;",
    "servise_card1_page_ul1_li39": "комплекс упражнений из ЛФК.",
    "servise_card1_page_text11": "Противопоказания к мануальной терапии",
    "servise_card1_page_text12": "Мануальная терапия подходит большинству пациентов, однако есть и ограничения для ее проведения:",
    "servise_card1_page_ul1_li40": "острая фаза психических заболеваний;",
    "servise_card1_page_ul1_li41": "злокачественные новообразования;",
    "servise_card1_page_ul1_li42": "инфекционное воспаление различной локализации;",
    "servise_card1_page_ul1_li43": "повышенная или сильно сниженная температура тела;",
    "servise_card1_page_ul1_li44": "неконтролируемая гипо- и гипертония;",
    "servise_card1_page_ul1_li45": "свежая травма позвоночника;",
    "servise_card1_page_ul1_li46": "острое нарушение кровоснабжения спинного мозга.",
    "servise_card1_page_text13": "Практически все техники, используемые мануальным терапевтом, безболезненны, поэтому пациенты с комфортом проходят процедуры. В Центре телесной терапии цена мануальной терапии умеренная, а эффективность и польза для организма — на высшем уровне.",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    
  },
  "en": {
    "servise_card1_page": "Manual therapy",
    "servise_card1_page_text1": "Modern society is characterized by increased attention to health, but at the same time, various diseases have become “younger”. This is due to increased nervous tension, and with a long sitting position at work or, conversely, increased physical activity, as well as with the constant use of mobile gadgets, which provokes a change in posture. As a result, there are pinched nerves, overstrain and shortening of some muscles against the background of stretching and weakening of others, as well as an unnatural curvature of the spine and a violation of its structures. Manual therapy is used to deal with these problems.",
    "servise_card1_page_text2": "The essence of manual therapy",
    "servise_card1_page_text3": "Literally, manual therapy is translated as «treatment with hands.» This means that the doctor, with the help of his hands and special techniques, affects the musculoskeletal system in order to help treat current problems with it. The technique is completely non-surgical and does not require any injections. Although manual therapy is considered to be a section of alternative medicine, it is also used in traditional areas - orthopedics, neurology, neurophysiology. Also, some exercises and techniques were transferred to sports medicine and exercise therapy.",
    "servise_card1_page_text4": "Initially, manual therapy was aimed at treating only the musculoskeletal system. Now it also includes visceral osteopathy, which affects the internal organs, as well as craniosacral therapy, which affects the head.When do you need the help of a chiropractor?",
    "servise_card1_page_ul1": "Contact our Body Therapy Center for a consultation with a manual therapist in such cases:",
    "servise_card1_page_ul1_li1": "Spend a lot of time on the road, incl. driving a car and on trains.",
    "servise_card1_page_ul1_li2": "Occasionally or regularly lift large loads.",
    "servise_card1_page_ul1_li3": "After a sharp turn, there is discomfort in the back, neck, limbs.",
    "servise_card1_page_ul1_li4": "There is a feeling of numb hands, cold feet.",
    "servise_card1_page_ul1_li5": "You lead a sedentary lifestyle or sit a lot at work.",
    "servise_card1_page_ul1_li6": "You feel constrained physically and mentally.",
    "servise_card1_page_ul1_li7": "There is isolation, irritability, depression.",
    "servise_card1_page_ul1_li8": "There is excess weight.",
    "servise_card1_page_ul1_li9": "Muscles feel tight in the morning.",
    "servise_card1_page_ul1_li10": "There is a lot of stress at work or in everyday life.",
    "servise_card1_page_ul1_li11": "You train in the gym, and after classes there is pain and discomfort in the body.",
    "servise_card1_page_text5": "Indications for the use of manual therapy",
    "servise_card1_page_text6": "We recommend signing up for manual therapy in Tashkent at our Body Therapy Center if there are such indications:",
    "servise_card1_page_ul1_li12": "pain and discomfort in the back - often provoked by osteochondrosis, hyperlordosis, scoliosis;",
    "servise_card1_page_ul1_li13": "hypertension or hypotension;",
    "servise_card1_page_ul1_li14": "insomnia;",
    "servise_card1_page_ul1_li15": "dizziness, migraine;",
    "servise_card1_page_ul1_li16": "chronic fatigue and high fatigue;",
    "servise_card1_page_ul1_li17": "weakness and numbness in the limbs;",
    "servise_card1_page_ul1_li18": "rachiocampsis;",
    "servise_card1_page_ul1_li19": "herniated discs;",
    "servise_card1_page_ul1_li20": "radiculitis",
    "servise_card1_page_ul1_li21": "neck lumbago;",
    "servise_card1_page_ul1_li22": "intercostal neuralgia;",
    "servise_card1_page_ul1_li23": "pain in the coccyx;",
    "servise_card1_page_ul1_li24": "displacement of intervertebral discs;",
    "servise_card1_page_ul1_li25": "osteochondrosis, which is manifested by headaches, pains in the heart, malfunctions of internal organs;",
    "servise_card1_page_ul1_li26": "arthrosis, reducing the amplitude of joint movements;",
    "servise_card1_page_ul1_li27": "limitation of mobility due to muscle strain",
    "servise_card1_page_ul1_li28": "sustained muscle spasms;",
    "servise_card1_page_ul1_li29": "recovery after injuries on the musculoskeletal system;",
    "servise_card1_page_ul1_li30": "neurosis and neurasthenia;",
    "servise_card1_page_ul1_li31": "cardiopsychoneurosis;",
    "servise_card1_page_ul1_li32": "decrease in the quality of vision, deterioration of memory and attention.",
    "servise_card1_page_text7": "The difference between manual therapy and massage",
    "servise_card1_page_text8": "It is a mistake to equate manual therapy with massage. they are radically different. Massage movements are aimed at working out soft tissues, and the actions of a chiropractor are aimed at the spine, joints and bones. Massage can help relieve tension in the muscles and relieve pain from curvature of the spine. But manual therapy helps to eliminate the causes of these manifestations, so it has a stronger effect on the body. That is why treatment by hands should be carried out only by a doctor with sufficient experience after examining the patient and taking an anamnesis.",
    "servise_card1_page_text9": "Methods of treatment in manual therapy",
    "servise_card1_page_text10": "For each patient, the doctor selects a set of techniques individually in order to achieve a pronounced positive result in a short time and alleviate the patient's condition. The main attention of the specialist is directed to the treatment of neurological manifestations of diseases, and in the future - to the rehabilitation of the patient. For this, the following methods are used:",
    "servise_card1_page_ul1_li33": "manual diagnostics and examination;",
    "servise_card1_page_ul1_li34": "manual therapy of joints and spinal column;",
    "servise_card1_page_ul1_li35": "acupuncture;",
    "servise_card1_page_ul1_li36": "post-isometric relaxation;",
    "servise_card1_page_ul1_li37": "MET;",
    "servise_card1_page_ul1_li38": "hatha yoga exercises;",
    "servise_card1_page_ul1_li39": "a set of exercises from exercise therapy.",
    "servise_card1_page_text11": "Contraindications for manual therapy",
    "servise_card1_page_text12": "Manual therapy is suitable for most patients, but there are limitations to its implementation:",
    "servise_card1_page_ul1_li40": "acute phase of mental illness;",
    "servise_card1_page_ul1_li41": "malignant neoplasms;",
    "servise_card1_page_ul1_li42": "infectious inflammation of various localization;",
    "servise_card1_page_ul1_li43": "elevated or severely reduced body temperature;",
    "servise_card1_page_ul1_li44": "uncontrolled hypo- and hypertension;",
    "servise_card1_page_ul1_li45": "fresh spinal injury;",
    "servise_card1_page_ul1_li46": "acute violation of the blood supply to the spinal cord.",
    "servise_card1_page_text13": "Almost all the techniques used by a chiropractor are painless, so patients are comfortable undergoing procedures. In the Center for Physical Therapy, the price of manual therapy is moderate, and the effectiveness and benefits for the body are at the highest level.",
    "servise_card2_page": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

  },
};

const langElements = document.querySelectorAll('.lang');

function changeLanguage(language) {
  selectedLanguage = language;
  langElements.forEach(el => {
    el.textContent = langData[selectedLanguage][el.getAttribute('key')];
  });
}



// Tilni qayta belgilash
let selectedLanguage = 'ru';
langElements.forEach(el => {
  el.textContent = langData[selectedLanguage][el.getAttribute('key')];
});

const langButtons = document.querySelectorAll('.lang-button');
langButtons.forEach(btn => {
btn.addEventListener('click', () => {
  changeLanguage(btn.dataset.lang);
  langButtons.forEach(btn => {
    btn.classList.remove('active_lang');
  });
  btn.classList.add('active_lang');
});
});
